spring:
    config:
        activate:
            on-profile: default
    data:
        mongodb:
#            authentication-database: admin
#            username: events
#            password: events
            database: stanari
            port: 27017
#            host: 192.168.1.7
            host: 127.0.0.1
#            uri: mongodb://192.168.1.7:27017
            auto-index-creation: true
    output:
        ansi:
            enabled: ALWAYS

logging:
    level:
        root: "info"
        org.springframework.web: "info"
        org.mongodb: "error"